# Generated by Django 5.2.5 on 2025-08-18 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_sources', models.JSONField()),
                ('fields', models.JSONField()),
                ('filters', models.JSONField(default=list)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF Document'), ('Excel', 'Excel Spreadsheet'), ('CSV', 'CSV File'), ('PowerPoint', 'PowerPoint Presentation')], default='PDF', max_length=20)),
                ('template', models.CharField(choices=[('business_standard', 'Business Standard'), ('executive_summary', 'Executive Summary'), ('detailed_analysis', 'Detailed Analysis'), ('financial', 'Financial Report'), ('marketing', 'Marketing Report')], default='business_standard', max_length=50)),
                ('layout', models.CharField(choices=[('table', 'Table Layout'), ('chart', 'Chart Layout'), ('dashboard', 'Dashboard Layout'), ('summary', 'Summary Layout')], default='table', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('attach_format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_distribution', to='reports.report')),
            ],
            options={
                'verbose_name': 'Email Distribution',
                'verbose_name_plural': 'Email Distributions',
                'db_table': 'email_distributions',
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('email_status', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'db_table': 'report_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_execution', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
            },
        ),
    ]
