# Generated by Django 5.2.5 on 2025-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='table_relationships',
            field=models.JSONField(default=list),
        ),
    ]
