# Generated by Django 5.2.5 on 2025-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_table_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='calculated_fields',
            field=models.JSONField(default=list),
        ),
    ]
