# Generated by Django 5.2.5 on 2025-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_calculated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cte_definitions',
            field=models.JSONField(default=list),
        ),
    ]
